spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/itripdb?useUnicode=true&characterEncoding=utf-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:jingchao528}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
mybatis:
  mapper-locations: cn/itrip/itripdao/*Mapper.xml

logging:
  level:
    cn.itrip: debug
