spring:
  datasource:
    url: jdbc:mysql://192.168.9.14:3306/itripdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: jingchao528
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
mybatis:
  mapper-locations: cn/itrip/itripdao/*Mapper.xml
